
import javax.swing.JOptionPane;

public class Display extends javax.swing.JFrame {

    public Display() { start(); }
    
        private void start(){
            initComponents(); w.imageSizer(); 
            
            giveTrackList(); int track = getTrack(); 
            
            boolean animate = true; w.setAnimate(animate);
            
            if (track != 0) { w.setPlayMusic(true); }
            if (animate && track != 0) { w.m.setTrack(track); w.m.playAudio(); }
            
            w.setAudioShiftIntensity(0.30); w.setAudioRadiusIntensity(-0.60);

            w.setPoints(75); w.setN(3);
            w.setRadius(100.0); w.setPointSpeed(0.75); w.setShiftSpeed(1);
            w.setGrayScale(false); w.setSymetrical(true); w.setHueShift(true); 

            w.initNoise(); w.printNoise();

            if (animate) {

                w.initMove();
                w.initTime();
                w.timer.start();
            }
        }
        
        private int getTrack(){
            String input = JOptionPane.showInputDialog("Please enter a track number [1 - 9] (0 = no audio):", 0);
            int number = 0;
            try {
                number = Integer.parseInt(input);
            } catch (NumberFormatException e) {
                System.out.println(e);
            }
            return number;
        }
        
        private void giveTrackList(){
            String tracks = "01 - Crush The Flowers (The Wake)\n" +
                            "02 - He Saw The Light (Martin Dupont)\n" +
                            "03 - Love Action (The Human League)\n" +
                            "04 - Of Whales (Tona Walt Ohama)\n" +
                            "05 - I The Cheated (Lowlife)\n" +
                            "06 - p:machinery (Propaganda)\n" +
                            "07 - Escape: Polaris (Pete Namlook)\n" +
                            "08 - Europe After Rain (John Foxx)\n" +
                            "09 - Taking Shape (Kas Product)";
            JOptionPane.showMessageDialog(null, tracks);
        }     
        
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        w = new CEVGenCore();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wLayout = new javax.swing.GroupLayout(w);
        w.setLayout(wLayout);
        wLayout.setHorizontalGroup(
            wLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        wLayout.setVerticalGroup(
            wLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(w, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(w, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wMouseClicked
       w.screenShot(); System.out.println("Frame saved.");
    }//GEN-LAST:event_wMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CEVGenCore w;
    // End of variables declaration//GEN-END:variables
}
